### ISSUE TITLE
read and implement config

### ISSUE THREAD

**Issue by yunju2** [gitovep/gitove#12]
- [ ] default config file 포멧 정하기 (크게 3종류로 header, domain, keyword )
- [ ] package.json 대신 사용자 입력 값을 읽을 수 있도록 만들기

**Comment by ninthsun91** [comment]
혹시 네이밍을,

header > type
domain > scope

로 변경할 수 있을까요?

기존 노션에 적었던 네이밍이 다소 그 의미가 모호한거 같아서요. 아니면 type도 헤깔려서 commitType라고 보다 구체적으로 적는게 나으려나요?

**Comment by yunju2** [comment]
> 혹시 네이밍을,
> 
> header > type domain > scope
> 
> 로 변경할 수 있을까요?
> 
> 기존 노션에 적었던 네이밍이 다소 그 의미가 모호한거 같아서요. 아니면 type도 헤깔려서 commitType라고 보다 구체적으로 적는게 나으려나요?

사용자들이 플젝 의도가 커밋메세지 작성인것을 충분히 알지 않을까 싶어 type으로만 적어도 충분할 거 같다는 생각이 듭니다. 
&lt;type&gt;[scope]: &lt;keyword&gt; 
아니면 readme에 설명을 붙이면 어떨까 싶습니다.

**Comment by ninthsun91** [comment]
카톡으로 주신 요거 포멧에서 `type`, `scope`, `keyword` 아래처럼 복수형으로 변경하면 어떨까요?

```
exports.defaultConfig = [{
    types: {
        name:"feat",
        alias:"f",
        descriiption:"null"
    },
    scopes: {
        name:"null",
        alias:"null",
        description:"null"
    },
    keywords: {
        name:"null",
        alias:"null",
        description:"null"
    }
}]
```

**Comment by ninthsun91** [comment]
@gitovep/plus 

`keyword`도 `replace`로 바꾸고, `type`, `scope`, `replace`안에 들어가는 형태를 다 퉁쳐서 `keyword`라고 부르는게 어떨가 싶어요.


```
exports.defaultConfig = [{
    type: {
        name:"feat",
        alias:"f",
        descriiption:"null"
    },
    scope: {
        name:"null",
        alias:"null",
        description:"null"
    },
    replace: {
        name:"null",
        alias:"null",
        description:"null"
    }
}]

type KeywordConfig = {
  name: string;
  alias: string;
  description: string;
}
```

**Comment by waveinyu** [comment]
@ninthsun91 아까 메신저에서 @yunju2 님이 올려주신 config에서 `type`과 `emoji`는 합쳐달라고 요청하셨는데, 혹시 여기에서는 배제가 된 걸까요? 덧붙여 저는 현재 첨부해주신 config의 형식 자체는 각 요소들을 직관적으로 파악할 수 있다는 점이 좋습니다.

**Comment by ninthsun91** [comment]
> @ninthsun91 아까 메신저에서 @yunju2 님이 올려주신 config에서 `type`과 `emoji`는 합쳐달라고 요청하셨는데, 혹시 여기에서는 배제가 된 걸까요? 덧붙여 저는 현재 첨부해주신 config의 형식 자체는 각 요소들을 직관적으로 파악할 수 있다는 점이 좋습니다.

#17 요거 참고하시면 될 것 같아요.

emoji가 어차피 허재코치님이 보여주신 예시처럼 예약어로 교체하기 위한 목적이라면 `replace` 필드와 통합이 가능해보였어요. 혹은, `type`에 넣을 수도 있을거구요.

**Comment by codeing999** [comment]
@ninthsun91 님의 위 댓글과 #17 를 보았을 때,

type과 scope 를 제가 사용하는 것이고
replace를 @waveinyu 님이 사용하는 것으로 이해되네요
