### ISSUE TITLE
Update execa & inquirer version

### ISSUE THREAD

**Issue by hoduulmu** [gitovep/gitove#23]
새욱님이 Esm 모듈로 변경하셨으니 esm only 문제로 업데이트 못한 두 라이브러리 버전 업데이트 진행해도 되지 않을까 싶어서 이슈 만들었습니다

아무나 이슈 가져가서 작업하셔도 되지 않을까 싶어요

**Comment by ninthsun91** [comment]
요거 inquirer는 제가 업데이트 했고 다음번 PR에 포함해서 올릴 예정이에요.

**Comment by hoduulmu** [comment]
그럼 제가 그냥 지금 올린 피알에 execa 버전 업데이트 포함할게요
