### ISSUE TITLE
Change PR Template

### ISSUE THREAD

**Issue by hoduulmu** [gitovep/gitove#25]
- [ ] Pr template 오픈 소스에 맞게 형식 변경 (아래 세욱님 코멘트 확인)
- [ ] 영어로 작성

**Comment by ninthsun91** [comment]
영어로 번역하기보다 템플릿 형식도 조금 바꾸면 좋을 것 같아요.

현재는 코드 리뷰에 포커싱을 맞추고 있다면, 조금 더 오픈소스에 맞게
- 문제 혹은 바꾸려는 이유
- 변경 내용
- 관련이슈 등 레퍼런스

정도로 정리해도 되지 않나 싶긴합니다.
요건 하시는 분이 다른 오픈소스들 참고해서 뭐 잘 정해주세요ㅋㅋㅋ
