### ISSUE TITLE
Create main branch CD pipeline

### ISSUE THREAD

**Issue by ninthsun91** [gitovep/gitove#35]
## Requirements

- use Github Action
- target: release branch PR merge
- build and publish

npm package security tokens will be soon updated in repo secrets
sementic version tags can be added

**Comment by hoduulmu** [comment]
여기서 cd는 npm 라이브러리에 자동 배포되는 개념인가요?

**Comment by ninthsun91** [comment]
@hoduulmu 
> 여기서 cd는 npm 라이브러리에 자동 배포되는 개념인가요?

네 맞아요.

**Comment by ninthsun91** [comment]
Will be reopned after publishing the project and versioning rules are set
