### ISSUE TITLE
wrapping git

### ISSUE THREAD

**Issue by hoduulmu** [gitovep/gitove#5]
최종적으로 생성된 메시지를 git commit에 전달
이때, 커밋 메시지 여러줄 작성해야하며 제목과 내용 사이에는 한줄이 떨어져 있어야함

* [x] 깃 랩핑이 정확하게 무엇인지 알아보기
* [x] [gitmoji에서 사용](https://github.com/carloscuesta/gitmoji-cli/blob/master/src/commands/commit/withClient/index.js)한 [execa](https://www.npmjs.com/package/execa) 알아보기
* [x] 구현 방법 정하기
* [x] 구현

**Comment by hoduulmu** [comment]
@ninthsun91 
@yunju2 
@waveinyu 
@codeing999 

<img width="1495" alt="스크린샷 2023-08-08 오후 12 03 53" src="https://github.com/gitovep/gitove/assets/62408879/6a0136be-abd0-461b-a337-bccbe5fe4db9">

`pnpm run start` 할 시 `ERR_REQUIRE_ESM` 발생
-> execa 6 이상(현재 7.2.0) 부터는 esm only인 것 때문인듯? 
https://github.com/sindresorhus/execa/issues/489

[관련 카카오스타일 기술블로그 링크](https://devblog.kakaostyle.com/ko/2022-04-09-1-esm-problem/)
프로젝트를 ESM으로 바꾸거나 해야한다는 말도 있고 한대 일반적인 해결책이나 방향을 제가 잘알지 못해서 의견을 부탁드려요

일단 링크한 이슈에서 execa 버전을 다운그레이드해 `5.1.1`로 진행하면 된다고 해서 그렇게 진행하도록 하겠습니다

**Comment by ninthsun91** [comment]
굳이 타라이브러리 의존성을 고려할 필요가 없는 상황이긴해서, 이러면 ESM으로 빌드하는게 나으려나요?

요런것도 이따 코치님께 한번 여쭤보죠

**Comment by waveinyu** [comment]
ㄴㅇㄹㄴㅇㄹ

**Comment by ninthsun91** [comment]
이거 생각해보니까 커밋 바디 부분 어떻게 데이터가 들어가있을지 애매하실거 같은데 inquirer에서 어떻게 멀티라인 답변 받아올지 다시 봐야할거 같아요.

일단은 단일라인 형태의 string타입 데이터라고 생각하고 구현 해놓고, 멀티라인 관련 로직 정리가 되면 그때 가서 다시 바꾸면 어떨까요?

inquirer 쓰기 전에는 Array<string>으로 받아서 현재 commitMessage 맵객체에 넣을 생각이었어요.

**Comment by hoduulmu** [comment]
> 이거 생각해보니까 커밋 바디 부분 어떻게 데이터가 들어가있을지 애매하실거 같은데 inquirer에서 어떻게 멀티라인 답변 받아올지 다시 봐야할거 같아요.
> 
> 일단은 단일라인 형태의 string타입 데이터라고 생각하고 구현 해놓고, 멀티라인 관련 로직 정리가 되면 그때 가서 다시 바꾸면 어떨까요?
> 
> inquirer 쓰기 전에는 Array으로 받아서 현재 commitMessage 맵객체에 넣을 생각이었어요.

일단 그럼 commitMessage -> string 으로 변환하는 코드르르 따로 빼서 관리해서 추후 변경에 쉽게 대응할 수 있도록 해놓겠습니다!

**Comment by hoduulmu** [comment]
* [ ] commitMessage -> string
* [ ] make git command
