### ISSUE TITLE
error in getting dirname

### ISSUE THREAD

**Issue by codeing999** [gitovep/gitove#57]
# Error

```shell
file:///C:/Users/mero/Desktop/projects/gitove/lib/readConfig/getConfigfile.js:5
const __filename = fileURLToPath(require('url').pathToFileURL(__filename).toString());      
                   ^

ReferenceError: require is not defined in ES module scope, you can use import instead       
This file is being treated as an ES module because it has a '.js' file extension and 'C:\Users\mero\Desktop\projects\gitove\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///C:/Users/mero/Desktop/projects/gitove/lib/readConfig/getConfigfile.js:5:20   
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

@yunju2 님이 구현한 설정파일 읽어오는 모듈을 사용하도록 제 insertHeader 함수를 변경했으나
해당 모듈을 사용하면 디렉토리 경로를 얻어오는 부분에서 에러가 발생.

# Additional context

@ninthsun91 님과 상의해보니 
해당 코드는 cjs에서 사용하는  "__dirname" 키워드가 esm 모듈에서는 그대로 사용될 수 없어서
esm 모듈에서 위를 대체하여 사용하는 코드인데,
동일한 코드를 다른 esm 모듈 프로젝트에서 사용했을 땐 에러가 나지 않고 정상적으로 작동되지만
현재 저희 프로젝트는 다른 패키지들과 함께 사용되다보니
이 부분도  빌드 시에 별도의 설정이 필요한 것으로 보입니다.

일단, 그래서 토요일까지는 이 문제를 해결하기에 시간이 부족할 것으로 판단하여
insertHeader의 변경은 보류하고 지금은 default config만 읽는 상태로 두겠습니다.

**Comment by ninthsun91** [comment]
정리 감사합니다
