### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by yunju2** [gitovep/gitove#60]
### Description of the problem

- [ ]  add info spec in configuration section

### Solution

Update README.md to include how to update config.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by ninthsun91** [comment]
![image](https://github.com/gitovep/gitove/assets/50778955/4a9043ab-e3d3-4057-ad4c-5f385d635369)

리드미 로고 이거로 바꿔주세요~

**Comment by yunju2** [comment]
행동강령도 추가해서 올리겠습니다.
